remote_theme: rundocs/jekyll-rtd-theme

author: AyanAmy

# folders sort
readme_index:
  with_frontmatter: true

meta:
  key2: value2

google:
  gtag:
  adsense:

mathjax: # this will prased to json, default: {}

mermaid:
  custom: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  initialize: # this will prased to json, default: {}

scss:   # also _includes/extra/styles.scss
script: # also _includes/extra/script.js

translate:
  # shortcodes
  danger:
  note:
  tip:
  warning:
  # 404
  not_found:
  # copyright
  revision:
  # search
  searching:
  search:
  search_docs:
  search_results:
  search_results_found: # the "#" in this translate will replaced with results size!
  search_results_not_found:

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - github-pages

script: |
  document.querySelector('.copyright').querySelector('a').innerText = 'JuneY';
  if(document.querySelector('.language-flow')){
    doThis();
  }

  async function doThis() {
    await setHeaders();
    var checkExist = setInterval(async ()=> {
      if (typeof flowchart !== 'undefined') {
        clearInterval(checkExist);
        render();
        console.log("rendered flowcharts");
      }
    }, 100);
  };
  async function setHeaders() {
    var script1 = document.createElement('script');
    script1.src = "https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js";
    document.head.appendChild(script1);

    var script2 = document.createElement('script');
    script2.src = "https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.15.0/flowchart.min.js";
    document.head.appendChild(script2);
    return;
  };
  function render() {
    var list = document.querySelectorAll('.language-flow');
    for (i=0; i<list.length;i++) {
      var item = list[i];
      var parsed = item.innerText;
      var id = "diagram"+i;
      list[i].id=id;
      try {
        flowchart.parse(parsed).drawSVG(id, {'yes-text':'true', 'no-text':'false'});
        list[i].childNodes[1].nodeValue="";
        list[i].childNodes[0].style="max-width:100% !important; height:auto !important;";
      }
      catch (err) {
        document.location=document.location;
      }
    };
    return;
  };
  
  
  

  
